const DATA_URL='data/images.json';
const LFS_BASE='https://media.githubusercontent.com/media/LaxmanNepal/Photos/main/';
const THUMB_BASE='https://media.githubusercontent.com/media/LaxmanNepal/Photos/main/thumbnails/';
const FAVORITES_KEY='laxman-photos-favorites-v1';
let photos=[],filtered=[],index=0,zoom=1,startX=0,startY=0,pinchStart=0,dragX=0,dragY=0;
let library='all',filter='all',query='',albumFolder='';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const favorites=new Set(JSON.parse(localStorage.getItem(FAVORITES_KEY)||'[]'));
function saveFavorites(){localStorage.setItem(FAVORITES_KEY,JSON.stringify([...favorites]));updateFavoriteCount()}
function photoKey(p){return p.path||p.url||p.name}
function isFavorite(p){return favorites.has(photoKey(p))}
function toggleFavorite(p){if(!p)return;const k=photoKey(p);isFavorite(p)?favorites.delete(k):favorites.add(k);saveFavorites();updateFavoriteCount();applyFilters()}
function updateFavoriteCount(){$('favoriteCount').textContent=favorites.size}
function imageUrl(photo,thumbnail=false){const path=photo?.path||photo?.url||'';if(/^https?:\/\//i.test(path))return path;const clean=path.replace(/^\.\//,'');if(thumbnail&&photo?.thumbnail)return THUMB_BASE+photo.thumbnail.replace(/^thumbnails\//,'').split('/').map(encodeURIComponent).join('/');return LFS_BASE+clean.split('/').map(encodeURIComponent).join('/')}
function formatBytes(bytes){if(!Number.isFinite(bytes)||bytes<=0)return '';const units=['B','KB','MB','GB','TB'];let i=0,n=bytes;while(n>=1024&&i<units.length-1){n/=1024;i++}return `${n.toFixed(n>=100||i===0?0:1)} ${units[i]}`}
function dateObj(p){const d=new Date(p.date||p.modified||0);return Number.isNaN(d.getTime())?null:d}
function photoDate(p){const d=dateObj(p);return d?d.toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'}):'Unknown date'}
function yearOf(p){return dateObj(p)?.getFullYear()||null}
function groupKey(p){const d=dateObj(p);return d?`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`:'Unknown'}
function groupLabel(key){if(key==='Unknown')return key;const[y,m]=key.split('-');return new Date(+y,+m-1,1).toLocaleDateString(undefined,{year:'numeric',month:'long'})}
function sortPhotos(arr){return [...arr].sort((a,b)=>(dateObj(b)?.getTime()||0)-(dateObj(a)?.getTime()||0))}
function orientation(p){if(!p.width||!p.height)return'unknown';const r=p.width/p.height;if(Math.abs(r-1)<.08)return'square';return r>1?'landscape':'portrait'}
function folderOf(p){const raw=String(p.path||'').replace(/^\.\//,'').replace(/^images\//,'');const parts=raw.split('/').filter(Boolean);return parts.length>1?parts.slice(0,-1).join('/'):'Library'}
function albumName(folder){return folder==='Library'?'All Library':folder.split('/').pop().replace(/[-_]+/g,' ')}
function baseLibrary(){if(library==='favorites')return photos.filter(isFavorite);if(library==='recent'){const cutoff=Date.now()-30*86400000;return photos.filter(p=>(dateObj(p)?.getTime()||0)>=cutoff).slice(0,100)}if(library==='album')return photos.filter(p=>folderOf(p)===albumFolder);return photos}
function applyFilters(){let arr=baseLibrary();if(query)arr=arr.filter(p=>[p.name,p.path,p.date,p.modified,p.year,p.month,folderOf(p)].filter(Boolean).join(' ').toLowerCase().includes(query));if(filter!=='all')arr=arr.filter(p=>filter==='large'?(p.size||0)>=5*1024*1024:orientation(p)===filter);filtered=sortPhotos(arr);render()}
async function load(){try{const r=await fetch(`${DATA_URL}?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error('index');const d=await r.json();photos=sortPhotos((d.images||[]).map(p=>({...p,url:imageUrl(p),thumbUrl:imageUrl(p,true)})));$('count').textContent=photos.length;$('updated').textContent=d.generated_at?`Updated ${new Date(d.generated_at).toLocaleDateString()}`:'Updated automatically';updateStats();updateFavoriteCount();renderYears();renderAlbums();renderMemories();applyFilters();openHashRoute()}catch(e){$('updated').textContent='Waiting for photo index'}finally{$('loading').classList.add('hidden');if(!photos.length)$('empty').classList.remove('hidden')}}
function makeCard(p,i){const c=document.createElement('article');c.className='card';const img=document.createElement('img');img.loading=i<12?'eager':'lazy';img.fetchPriority=i<6?'high':'auto';img.decoding='async';img.src=p.thumbUrl||p.url;img.alt=p.name||'Photo';img.onerror=()=>{if(img.src!==p.url){img.src=p.url;return}img.classList.add('load-error')};c.append(img);const fav=document.createElement('button');fav.className=`card-favorite${isFavorite(p)?' active':''}`;fav.textContent=isFavorite(p)?'♥':'♡';fav.onclick=e=>{e.stopPropagation();toggleFavorite(p)};c.append(fav);const info=document.createElement('div');info.className='card-info';const title=document.createElement('strong');title.textContent=p.name||'Photo';const meta=document.createElement('small');meta.textContent=[photoDate(p),formatBytes(p.size),p.width&&p.height?`${p.width}×${p.height}`:''].filter(Boolean).join(' · ');info.append(title,meta);c.append(info);c.onclick=()=>openViewer(i,c);return c}
function render(){const g=$('gallery');g.innerHTML='';$('resultCount').textContent=`${filtered.length} ${filtered.length===1?'photo':'photos'}`;if(!filtered.length){$('empty').classList.remove('hidden');$('emptyText').textContent=library==='favorites'?'No favorites yet. Tap ♡ on any photo to save it on this device.':library==='recent'?'No photos were added or updated in the last 30 days.':'No photos match the current filters.';return}$('empty').classList.add('hidden');if(document.body.classList.contains('grid-view')){filtered.forEach((p,i)=>g.append(makeCard(p,i)));return}const groups=new Map();filtered.forEach((p,i)=>{const k=groupKey(p);if(!groups.has(k))groups.set(k,[]);groups.get(k).push({p,i})});for(const[key,items]of groups){const s=document.createElement('section');s.className='month-section';const h=document.createElement('h2');h.className='month-title';h.innerHTML=`<span>${esc(groupLabel(key))}</span><small>${items.length}</small>`;s.append(h);const grid=document.createElement('div');grid.className='month-grid';items.forEach(({p,i})=>grid.append(makeCard(p,i)));s.append(grid);g.append(s)}}
function updateStats(){const size=photos.reduce((n,p)=>n+(Number(p.size)||0),0);const years=new Set(photos.map(yearOf).filter(Boolean));$('statPhotos').textContent=photos.length;$('statSize').textContent=formatBytes(size)||'0 B';$('statYears').textContent=years.size;$('statLatest').textContent=photos[0]?photoDate(photos[0]):'—'}
function renderYears(){const map=new Map();photos.forEach(p=>{const y=yearOf(p);if(y)map.set(y,(map.get(y)||0)+1)});const panel=$('yearPanel');panel.innerHTML='<div class="year-heading">Browse by year</div>';[...map.entries()].sort((a,b)=>b[0]-a[0]).forEach(([y,n])=>{const b=document.createElement('button');b.className='year-card';b.innerHTML=`<strong>${y}</strong><span>${n} photos</span>`;b.onclick=()=>selectQuery(String(y),String(y));panel.append(b)})}
function renderAlbums(){const map=new Map();photos.forEach(p=>{const f=folderOf(p);if(!map.has(f))map.set(f,[]);map.get(f).push(p)});const panel=$('albumPanel');panel.innerHTML='<div class="section-heading"><span>Albums</span><small>Automatic from folders</small></div>';[...map.entries()].sort((a,b)=>b[1].length-a[1].length).forEach(([folder,items])=>{const b=document.createElement('button');b.className='album-card';const cover=items[0];b.innerHTML=`<img src="${esc(cover.thumbUrl||cover.url)}" alt=""><span class="album-overlay"></span><div><strong>${esc(albumName(folder))}</strong><small>${items.length} photos</small></div>`;b.onclick=()=>selectAlbum(folder);panel.append(b)})}
function renderMemories(){const panel=$('memoryPanel');const now=new Date();const md=now.getMonth(),dd=now.getDate();const today=photos.filter(p=>{const d=dateObj(p);return d&&d.getMonth()===md&&d.getDate()===dd});const month=photos.filter(p=>{const d=dateObj(p);return d&&d.getMonth()===md});panel.innerHTML='<div class="section-heading"><span>Memories</span><small>From your photo history</small></div>';const make=(title,sub,items,mode)=>{const b=document.createElement('button');b.className='memory-card';const cover=items[0];b.innerHTML=cover?`<img src="${esc(cover.thumbUrl||cover.url)}" alt=""><span class="memory-overlay"></span><div><strong>${esc(title)}</strong><small>${esc(sub)}</small></div>`:`<div class="memory-empty"><strong>${esc(title)}</strong><small>No matching photos</small></div>`;if(items.length)b.onclick=()=>showMemory(items,title,mode);panel.append(b)};make('On This Day',`${today.length} photo${today.length===1?'':'s'} across your years`,today,'today');make('This Month',`${month.length} photo${month.length===1?'':'s'} from ${now.toLocaleDateString(undefined,{month:'long'})}`,month,'month')}
function showMemory(items,title,mode){filtered=sortPhotos(items);library='memory';albumFolder='';query='';filter='all';$('pageTitle').textContent=title;$('memoryPanel').classList.add('hidden');$('gallery').scrollIntoView({behavior:'smooth',block:'start'});render();}
function selectAlbum(folder){library='album';albumFolder=folder;query='';filter='all';$('searchInput').value='';$('pageTitle').textContent=albumName(folder);$('albumPanel').classList.add('hidden');$('memoryPanel').classList.add('hidden');$('yearPanel').classList.add('hidden');syncTabs();applyFilters();history.replaceState(null,'',`#album=${encodeURIComponent(folder)}`)}
function selectQuery(q,title){library='all';albumFolder='';query=q.toLowerCase();filter='all';$('searchInput').value=q;$('pageTitle').textContent=title;hidePanels();syncTabs();applyFilters()}
function hidePanels(){$('yearPanel').classList.add('hidden');$('albumPanel').classList.add('hidden');$('memoryPanel').classList.add('hidden')}
function syncTabs(){document.querySelectorAll('.library-tab').forEach(b=>b.classList.toggle('active',b.dataset.library===library));document.querySelectorAll('.filter-chip').forEach(b=>b.classList.toggle('active',b.dataset.filter===filter))}
function setLibrary(next){library=next;query='';albumFolder='';$('searchInput').value='';hidePanels();$('pageTitle').textContent=next==='favorites'?'Favorites':next==='recent'?'Recently Added':next==='years'?'Years':next==='albums'?'Albums':next==='memories'?'Memories':'All Photos';syncTabs();if(next==='years'){$('yearPanel').classList.remove('hidden');$('gallery').innerHTML='';$('resultCount').textContent='';return}if(next==='albums'){$('albumPanel').classList.remove('hidden');$('gallery').innerHTML='';$('resultCount').textContent='';return}if(next==='memories'){$('memoryPanel').classList.remove('hidden');$('gallery').innerHTML='';$('resultCount').textContent='';return}applyFilters();history.replaceState(null,'',location.pathname+location.search)}
function setFilter(next){filter=next;syncTabs();applyFilters()}
function applyTransform(){const img=$('viewerImg');img.style.transform=`translate3d(${dragX}px,${dragY}px,0) scale(${zoom})`;img.style.cursor=zoom>1?'grab':'zoom-in'}
function resetZoom(){zoom=1;dragX=dragY=0;applyTransform();$('zoomReset').textContent='100%'}
function setZoom(v){zoom=Math.min(4,Math.max(1,v));if(zoom===1)dragX=dragY=0;applyTransform();$('zoomReset').textContent=`${Math.round(zoom*100)}%`}
function animateOpen(card){const viewer=$('viewer'),content=$('viewer').querySelector('.viewer-content');if(!card||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const r=card.getBoundingClientRect(),v=content.getBoundingClientRect();const sx=Math.max(.18,Math.min(1,r.width/v.width)),sy=Math.max(.18,Math.min(1,r.height/v.height)),scale=Math.min(sx,sy);const cx=r.left+r.width/2,cy=r.top+r.height/2;const vx=v.left+v.width/2,vy=v.top+v.height/2;content.animate([{transform:`translate3d(${cx-vx}px,${cy-vy}px,0) scale(${scale})`,opacity:.15,filter:'blur(2px)'},{transform:'translate3d(0,0,0) scale(1)',opacity:1,filter:'blur(0)'}],{duration:420,easing:'cubic-bezier(.16,1,.3,1)',fill:'both'});viewer.animate([{opacity:0},{opacity:1}],{duration:260,easing:'ease-out',fill:'both'})}
function animateClose(){const viewer=$('viewer'),content=viewer.querySelector('.viewer-content');if(viewer.dataset.closing==='1')return Promise.resolve();if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){viewer.classList.add('hidden');return Promise.resolve()}const card=[...document.querySelectorAll('.card')].find(c=>c.querySelector('img')?.alt===(filtered[index]?.name||'Photo'));if(!card){viewer.classList.add('hidden');return Promise.resolve()}const r=card.getBoundingClientRect(),v=content.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,vx=v.left+v.width/2,vy=v.top+v.height/2,scale=Math.max(.18,Math.min(r.width/v.width,r.height/v.height));viewer.dataset.closing='1';const a=content.animate([{transform:'translate3d(0,0,0) scale(1)',opacity:1,filter:'blur(0)'},{transform:`translate3d(${cx-vx}px,${cy-vy}px,0) scale(${scale})`,opacity:.1,filter:'blur(2px)'}],{duration:330,easing:'cubic-bezier(.7,0,.84,0)',fill:'both'});return a.finished.catch(()=>{}).then(()=>{viewer.classList.add('hidden');viewer.dataset.closing='0';content.style.transform='';content.style.opacity='';viewer.style.opacity='';})}
function updateViewer(card){const p=filtered[index];if(!p)return;resetZoom();$('viewerImg').src=p.url;$('viewerImg').alt=p.name||'Photo';$('favoriteBtn').textContent=isFavorite(p)?'♥':'♡';$('favoriteBtn').classList.toggle('active',isFavorite(p));$('viewerCaption').innerHTML=`<strong>${esc(p.name||'Photo')}</strong><small>${esc([photoDate(p),formatBytes(p.size),p.width&&p.height?`${p.width}×${p.height}`:''].filter(Boolean).join(' · '))}</small>`;$('detailsPanel').innerHTML=`<b>Photo details</b><dl><dt>Name</dt><dd>${esc(p.name)}</dd><dt>Date</dt><dd>${esc(photoDate(p))}</dd><dt>Size</dt><dd>${esc(formatBytes(p.size)||'Unknown')}</dd><dt>Dimensions</dt><dd>${p.width&&p.height?`${p.width} × ${p.height}`:'Unknown'}</dd><dt>Orientation</dt><dd>${orientation(p)}</dd><dt>Album</dt><dd>${esc(albumName(folderOf(p)))}</dd><dt>Path</dt><dd>${esc(p.path||'')}</dd></dl>`;$('detailsPanel').classList.add('hidden');$('viewer').classList.remove('hidden');document.body.style.overflow='hidden';preload(1);preload(-1);requestAnimationFrame(()=>animateOpen(card))}
function openViewer(i,card){index=i;updateViewer(card)}
async function closeViewer(){await animateClose();document.body.style.overflow='';resetZoom()}
function move(n){if(!filtered.length)return;index=(index+n+filtered.length)%filtered.length;updateViewer()}
function preload(n){const p=filtered[(index+n+filtered.length)%filtered.length];if(p){const im=new Image();im.src=p.url}}
async function downloadPhoto(){const p=filtered[index];try{const r=await fetch(p.url),b=await r.blob(),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=p.name||'photo';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}catch{window.open(p.url,'_blank')}}
async function sharePhoto(){const p=filtered[index];try{if(navigator.share)await navigator.share({title:p.name||'Photo',text:'Laxman Nepal Photos',url:p.url});else await navigator.clipboard.writeText(p.url)}catch{}}
function openHashRoute(){const m=location.hash.match(/^#album=(.+)$/);if(m){const folder=decodeURIComponent(m[1]);if(photos.some(p=>folderOf(p)===folder))selectAlbum(folder)}}
$('searchBtn').onclick=()=>{$('searchBar').classList.toggle('hidden');if(!$('searchBar').classList.contains('hidden'))$('searchInput').focus()};
$('clearSearch').onclick=()=>{$('searchInput').value='';query='';applyFilters()};
$('searchInput').oninput=e=>{query=e.target.value.trim().toLowerCase();library='all';albumFolder='';$('pageTitle').textContent='Search results';syncTabs();applyFilters()};
document.querySelectorAll('.library-tab').forEach(b=>b.onclick=()=>setLibrary(b.dataset.library));
document.querySelectorAll('.filter-chip[data-filter]').forEach(b=>b.onclick=()=>setFilter(b.dataset.filter));
$('clearFilters').onclick=()=>{query='';filter='all';library='all';albumFolder='';$('searchInput').value='';$('pageTitle').textContent='All Photos';hidePanels();syncTabs();applyFilters();history.replaceState(null,'',location.pathname+location.search)};
$('statsBtn').onclick=()=>$('statsPanel').classList.toggle('hidden');
$('timelineBtn').onclick=()=>{document.body.classList.remove('grid-view');$('timelineBtn').classList.add('active');$('gridBtn').classList.remove('active');render()};
$('gridBtn').onclick=()=>{document.body.classList.add('grid-view');$('gridBtn').classList.add('active');$('timelineBtn').classList.remove('active');render()};
$('closeViewer').onclick=closeViewer;$('prevBtn').onclick=()=>move(-1);$('nextBtn').onclick=()=>move(1);$('zoomIn').onclick=()=>setZoom(zoom+.5);$('zoomOut').onclick=()=>setZoom(zoom-.5);$('zoomReset').onclick=resetZoom;$('downloadBtn').onclick=downloadPhoto;$('shareBtn').onclick=sharePhoto;$('detailsBtn').onclick=()=>$('detailsPanel').classList.toggle('hidden');
$('favoriteBtn').onclick=()=>{const p=filtered[index];toggleFavorite(p);$('favoriteBtn').textContent=isFavorite(p)?'♥':'♡';$('favoriteBtn').classList.toggle('active',isFavorite(p))};
$('viewer').onclick=e=>{if(e.target===$('viewer'))closeViewer()};
$('viewerImg').addEventListener('dblclick',()=>setZoom(zoom>1?1:2));
$('viewerImg').addEventListener('wheel',e=>{e.preventDefault();setZoom(zoom+(e.deltaY<0?.25:-.25))},{passive:false});
$('viewerImg').addEventListener('pointerdown',e=>{if(zoom<=1){startX=e.clientX;startY=e.clientY;return}$('viewerImg').setPointerCapture(e.pointerId);startX=e.clientX-dragX;startY=e.clientY-dragY});
$('viewerImg').addEventListener('pointermove',e=>{if(zoom<=1||!e.buttons)return;dragX=e.clientX-startX;dragY=e.clientY-startY;applyTransform()});
$('viewerImg').addEventListener('pointerup',()=>{if(zoom<=1)return;const dx=dragX,dy=dragY;if(Math.abs(dx)>120&&Math.abs(dx)>Math.abs(dy)){dragX=dragY=0;move(dx<0?1:-1)}});
$('viewerImg').addEventListener('touchstart',e=>{if(e.touches.length===1){startX=e.touches[0].clientX;startY=e.touches[0].clientY}else if(e.touches.length===2)pinchStart=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY)},{passive:true});
$('viewerImg').addEventListener('touchmove',e=>{if(e.touches.length===2){const d=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);if(pinchStart)setZoom(zoom+(d-pinchStart)/500);pinchStart=d}},{passive:true});
$('viewerImg').addEventListener('touchend',e=>{if(e.touches.length)return;const t=e.changedTouches[0],dx=t.clientX-startX,dy=t.clientY-startY;if(zoom===1&&Math.abs(dx)>70&&Math.abs(dx)>Math.abs(dy))move(dx<0?1:-1)});
document.onkeydown=e=>{if($('viewer').classList.contains('hidden'))return;if(e.key==='Escape')closeViewer();if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1);if(e.key==='+'||e.key==='=')setZoom(zoom+.5);if(e.key==='-')setZoom(zoom-.5)};
$('themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.theme=document.body.classList.contains('dark')?'dark':'light'};if(localStorage.theme==='dark')document.body.classList.add('dark');
let deferredPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').classList.remove('hidden')});$('installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('installBtn').classList.add('hidden')}};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
$('year').textContent=new Date().getFullYear();updateFavoriteCount();load();
