(() => {
  'use strict';
  const KEY='laxman-people-lens-v1', SIZE=16, DIST=48, BATCH=12;
  let cache={}; try{cache=JSON.parse(localStorage.getItem(KEY)||'{}')}catch(_){cache={}};
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const ps=()=>Array.isArray(window.photos)?window.photos:[];
  const src=p=>p.thumbUrl||p.thumbnail||p.url||'';
  const name=p=>p.filename||p.name||p.path?.split('/').pop()||'Photo';
  const key=p=>`${src(p)}|${p.modified||p.modifiedDate||p.file_size||''}`;
  function style(){if(document.getElementById('plStyle'))return;const s=document.createElement('style');s.id='plStyle';s.textContent=`.pl-modal{position:fixed;inset:0;z-index:10003;background:rgba(8,8,12,.72);backdrop-filter:blur(28px);display:flex;align-items:center;justify-content:center;padding:12px}.pl-card{width:min(1120px,100%);max-height:91vh;overflow:auto;border:1px solid rgba(255,255,255,.14);background:rgba(27,27,32,.92);border-radius:30px;padding:20px;color:#fff;box-shadow:0 35px 120px rgba(0,0,0,.5)}.pl-head{display:flex;justify-content:space-between;gap:12px;align-items:center}.pl-head h2{margin:0}.pl-head p{margin:5px 0 0;font-size:11px;opacity:.55}.pl-close,.pl-run{border:1px solid rgba(255,255,255,.14);background:rgba(255,255,255,.08);color:#fff;border-radius:12px;padding:9px 13px;cursor:pointer}.pl-note{margin:15px 0;font-size:11px;opacity:.55}.pl-progress{height:6px;background:rgba(255,255,255,.1);border-radius:9px;overflow:hidden}.pl-progress i{display:block;height:100%;width:0;background:#fff;transition:width .2s}.pl-status{font-size:12px;opacity:.7;margin:9px 0 14px}.pl-groups{display:grid;gap:15px}.pl-group{border:1px solid rgba(255,255,255,.1);border-radius:20px;padding:11px}.pl-title{display:flex;justify-content:space-between;font-size:12px;margin-bottom:10px;opacity:.8}.pl-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(125px,1fr));gap:8px}.pl-item{aspect-ratio:1;position:relative;overflow:hidden;border-radius:13px;background:#111}.pl-item img{width:100%;height:100%;object-fit:cover}.pl-item span{position:absolute;left:5px;right:5px;bottom:5px;background:rgba(0,0,0,.62);border-radius:6px;padding:3px 5px;font-size:9px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.pl-empty{text-align:center;padding:45px 10px;opacity:.6}@media(max-width:600px){.pl-card{padding:14px;border-radius:23px}.pl-grid{grid-template-columns:repeat(3,1fr)}}`;document.head.appendChild(s)}
  function load(src){return new Promise((res,rej)=>{const i=new Image();i.crossOrigin='anonymous';i.onload=()=>res(i);i.onerror=rej;i.src=src})}
  function hash(img,box){const c=document.createElement('canvas');c.width=SIZE;c.height=SIZE;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(img,box.x,box.y,box.width,box.height,0,0,SIZE,SIZE);const d=x.getImageData(0,0,SIZE,SIZE).data;let sum=0,g=[];for(let i=0;i<d.length;i+=4){const v=d[i]*.299+d[i+1]*.587+d[i+2]*.114;g.push(v);sum+=v}const a=sum/g.length;return g.map(v=>v>=a?'1':'0').join('')}
  function dist(a,b){let n=0;for(let i=0;i<a.length;i++)if(a[i]!==b[i])n++;return n}
  function save(){try{localStorage.setItem(KEY,JSON.stringify(cache))}catch(_) {}}
  function modal(){style();const m=document.createElement('div');m.className='pl-modal';m.id='plModal';m.innerHTML=`<div class="pl-card"><div class="pl-head"><div><h2>◉ People Lens</h2><p>On-device face detection + face-crop similarity. No photos are uploaded.</p></div><button class="pl-close">×</button></div><div class="pl-note">This uses your browser's native FaceDetector when available. It does not identify a person by name; it only groups visually similar detected face crops.</div><button class="pl-run" id="plRun">Analyze people</button><div class="pl-progress"><i id="plBar"></i></div><div class="pl-status" id="plStatus">Ready.</div><div class="pl-groups" id="plGroups"></div></div>`;document.body.appendChild(m);m.querySelector('.pl-close').onclick=()=>m.remove();m.querySelector('#plRun').onclick=()=>run(m);return m}
  async function run(m){const status=m.querySelector('#plStatus'),bar=m.querySelector('#plBar'),box=m.querySelector('#plGroups'),runBtn=m.querySelector('#plRun');if(!('FaceDetector' in window)){box.innerHTML='<div class="pl-empty">Your browser does not expose the native FaceDetector API. People Lens is kept disabled rather than sending photos to a third-party service.</div>';status.textContent='Native face detection unavailable.';return}runBtn.disabled=true;const detector=new FaceDetector({fastMode:true,maxDetectedFaces:10}), list=ps().filter(src), faces=[];for(let i=0;i<list.length;i+=BATCH){const batch=list.slice(i,i+BATCH);await Promise.all(batch.map(async p=>{try{const img=await load(src(p)),found=await detector.detect(img);for(let n=0;n<found.length;n++){const b=found[n].boundingBox;const pad=Math.max(b.width,b.height)*.35;const x=Math.max(0,b.x-pad),y=Math.max(0,b.y-pad),w=Math.min(img.naturalWidth-x,b.width+pad*2),h=Math.min(img.naturalHeight-y,b.height+pad*2);const k=`${key(p)}|${n}|${Math.round(b.x)}|${Math.round(b.y)}`;cache[k]=cache[k]||hash(img,{x,y,width:w,height:h});faces.push({p,k})}}catch(_){} }));bar.style.width=Math.round((Math.min(i+BATCH,list.length)/list.length)*100)+'%';status.textContent=`Scanning ${Math.min(i+BATCH,list.length)} of ${list.length} photos · ${faces.length} faces`;await new Promise(r=>setTimeout(r,20))}save();const groups=[],used=new Set();for(let i=0;i<faces.length;i++){if(used.has(i))continue;const g=[faces[i]];for(let j=i+1;j<faces.length;j++){if(used.has(j))continue;if(dist(cache[faces[i].k],cache[faces[j].k])<=DIST)g.push(faces[j])}if(g.length>=2){g.forEach(x=>used.add(faces.indexOf(x)));groups.push(g)}}groups.sort((a,b)=>b.length-a.length);box.innerHTML=groups.slice(0,40).map((g,gi)=>`<section class="pl-group"><div class="pl-title"><span>Person-like group ${gi+1}</span><span>${g.length} detections</span></div><div class="pl-grid">${g.slice(0,18).map(x=>`<div class="pl-item"><img loading="lazy" src="${esc(src(x.p))}" alt=""><span>${esc(name(x.p))}</span></div>`).join('')}</div></section>`).join('')||'<div class="pl-empty">No repeatable face groups were found.</div>';status.textContent=`Done · ${faces.length} faces detected · ${groups.length} groups`;runBtn.disabled=false}
  function button(){const t=document.querySelector('.toolbar');if(!t||document.getElementById('peopleLensBtn'))return;const b=document.createElement('button');b.id='peopleLensBtn';b.className='icon-btn';b.textContent='◉';b.title='People Lens';b.setAttribute('aria-label','People Lens');b.onclick=modal;t.insertBefore(b,document.getElementById('visualSearchBtn')||document.getElementById('themeBtn'))}
  function init(){button();setInterval(button,1600)} if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
