(()=>{
'use strict';
const DATA='data/images.json';
let photos=[];
const css=`
.smart-btn{border:0;border-radius:13px;height:36px;padding:0 13px;background:rgba(127,127,127,.11);color:inherit;font:600 13px Inter,sans-serif;cursor:pointer;transition:.2s transform,.2s background}.smart-btn:hover{transform:translateY(-1px);background:rgba(127,127,127,.17)}
.smart-modal{position:fixed;inset:0;z-index:1000;display:grid;place-items:center;padding:18px;background:rgba(10,10,14,.42);backdrop-filter:blur(22px);-webkit-backdrop-filter:blur(22px)}.smart-modal.hidden{display:none}.smart-card{width:min(760px,94vw);max-height:88vh;overflow:auto;border:1px solid rgba(127,127,127,.2);border-radius:28px;padding:22px;background:rgba(250,250,252,.9);color:#17171a;box-shadow:0 30px 90px rgba(0,0,0,.25)}body.dark .smart-card{background:rgba(28,28,31,.94);color:#f5f5f7}.smart-head{display:flex;justify-content:space-between;align-items:center;gap:12px}.smart-head h2{margin:0;font-size:24px}.smart-close{border:0;background:rgba(127,127,127,.12);border-radius:50%;width:38px;height:38px;font-size:22px;cursor:pointer;color:inherit}.smart-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:18px 0}.smart-stat{padding:16px;border-radius:18px;background:rgba(127,127,127,.09)}.smart-stat strong{display:block;font-size:22px}.smart-stat span{font-size:12px;opacity:.65}.smart-section{margin-top:18px}.smart-section h3{font-size:14px;margin:0 0 9px}.smart-list{display:grid;gap:8px}.smart-row{display:flex;justify-content:space-between;gap:12px;padding:11px 13px;border-radius:14px;background:rgba(127,127,127,.08);font-size:13px}.smart-row small{opacity:.6;text-align:right}.smart-note{font-size:12px;opacity:.62;margin:12px 0 0}@media(max-width:600px){.smart-grid{grid-template-columns:repeat(2,1fr)}.smart-card{padding:17px;border-radius:22px}}
`;
function inject(){if(document.getElementById('smart-style'))return;const s=document.createElement('style');s.id='smart-style';s.textContent=css;document.head.appendChild(s)}
function bytes(n){if(!n)return '0 B';const u=['B','KB','MB','GB','TB'];let i=0,x=n;while(x>=1024&&i<u.length-1){x/=1024;i++}return `${x.toFixed(i?1:0)} ${u[i]}`}
function folder(p){const x=(p.path||p.filename||'').replace(/^\.?\//,'').replace(/^images\//,'');const a=x.split('/');return a.length>1?a.slice(0,-1).join('/'):'Library'}
function possibleDuplicates(){const m=new Map();photos.forEach(p=>{const key=[p.file_size||p.size||0,p.width||0,p.height||0,p.file_type||p.type||''].join('|');if(key!=='0|0|0|')m.set(key,[...(m.get(key)||[]),p])});return [...m.values()].filter(g=>g.length>1).sort((a,b)=>b.length-a.length)}
function show(){document.getElementById('smart-modal')?.classList.remove('hidden')}
function hide(){document.getElementById('smart-modal')?.classList.add('hidden')}
function render(){const dup=possibleDuplicates();const missing=photos.filter(p=>!(p.width&&p.height));const folders=new Set(photos.map(folder));const years=new Set(photos.map(p=>String(p.year||'')).filter(Boolean));const size=photos.reduce((s,p)=>s+Number(p.file_size||p.size||0),0);const modal=document.createElement('div');modal.id='smart-modal';modal.className='smart-modal hidden';modal.innerHTML=`<div class="smart-card" role="dialog" aria-modal="true" aria-label="Smart Library"><div class="smart-head"><div><div style="font-size:11px;letter-spacing:.12em;opacity:.55">LIBRARY INTELLIGENCE</div><h2>Smart Library</h2></div><button class="smart-close" aria-label="Close">×</button></div><div class="smart-grid"><div class="smart-stat"><strong>${photos.length}</strong><span>Photos</span></div><div class="smart-stat"><strong>${bytes(size)}</strong><span>Total size</span></div><div class="smart-stat"><strong>${folders.size}</strong><span>Folders</span></div><div class="smart-stat"><strong>${years.size}</strong><span>Years</span></div></div><div class="smart-section"><h3>Possible duplicates</h3><div class="smart-list">${dup.length?dup.slice(0,12).map(g=>`<div class="smart-row"><span>${g.length} photos · ${bytes(Number(g[0].file_size||g[0].size||0))} each</span><small>${g.slice(0,2).map(p=>p.filename||p.path).join(' · ')}</small></div>`).join(''):'<div class="smart-row"><span>No obvious duplicate groups found</span><small>Based on size + dimensions + type</small></div>'}</div></div><div class="smart-section"><h3>Metadata health</h3><div class="smart-list"><div class="smart-row"><span>Complete dimensions</span><small>${photos.length-missing.length}/${photos.length}</small></div><div class="smart-row"><span>Possible duplicate groups</span><small>${dup.length}</small></div><div class="smart-row"><span>Folders indexed</span><small>${folders.size}</small></div></div></div><p class="smart-note">Duplicate detection is conservative: matching file size, dimensions and type means “possible duplicate”, not a guaranteed byte-for-byte duplicate.</p></div>`;document.body.appendChild(modal);modal.querySelector('.smart-close').onclick=hide;modal.addEventListener('click',e=>{if(e.target===modal)hide()})}
async function init(){inject();const toolbar=document.querySelector('.toolbar');if(!toolbar||document.getElementById('smartBtn'))return;const b=document.createElement('button');b.id='smartBtn';b.className='smart-btn';b.textContent='✦ Smart';b.title='Smart Library';toolbar.insertBefore(b,toolbar.firstChild);b.onclick=async()=>{show();if(!photos.length){try{const r=await fetch(`${DATA}?v=${Date.now()}`,{cache:'no-store'});photos=await r.json();render()}catch(e){hide();return}}else render()};document.addEventListener('keydown',e=>{if(e.key==='Escape')hide()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();