(() => {
  'use strict';
  const DATA_URL='data/images.json'; let photos=[],open=false,visionCache=new Map();
  const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
  const date=p=>new Date(p.date||p.modified_at||p.modified||0); const url=p=>p.url||p.path||'';
  const tokens=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim().split(/\s+/).filter(Boolean);
  async function loadVision(){try{const db=await new Promise((res,rej)=>{const r=indexedDB.open('laxman-photos-ai-v1');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});return await new Promise(res=>{const a=db.transaction('analyses','readonly').objectStore('analyses').getAll();a.onsuccess=()=>res(a.result||[])})}catch(e){return[]}}
  const score=(p,q)=>{const a=visionCache.get(p.path||p.url||p.name)||{};const text=[p.name,p.path,p.year,p.month,p.type,p.width,p.height,a.tags?.join(' '),a.labels?.join(' '),a.caption,a.ocr].join(' ').toLowerCase();let n=0;for(const t of tokens(q))if(text.includes(t))n+=t.length>2?3:1;return n};
  function parse(q){const x=q.toLowerCase().trim(),o={year:null,month:null,large:false,portrait:false,landscape:false,square:false};const y=x.match(/\b(20\d{2})\b/);if(y)o.year=+y[1];const months=['january','february','march','april','may','june','july','august','september','october','november','december'];months.forEach((m,i)=>{if(new RegExp(`\\b${m.slice(0,3)}|${m}\\b`).test(x))o.month=i+1});o.large=/\b(large|big|huge)\b/.test(x);o.portrait=/\b(portrait|vertical)\b/.test(x);o.landscape=/\b(landscape|horizontal|wide)\b/.test(x);o.square=/\bsquare\b/.test(x);return o}
  function match(p,a){const d=date(p),r=p.width&&p.height?p.width/p.height:0;if(a.year&&(p.year||d.getFullYear())!==a.year)return false;if(a.month&&!Number.isNaN(d)&&d.getMonth()+1!==a.month)return false;if(a.large&&(p.size||0)<5*1024*1024)return false;if(a.portrait&&!(r<.95))return false;if(a.landscape&&!(r>1.05))return false;if(a.square&&!(Math.abs(r-1)<.08))return false;return true}
  function run(q){const a=parse(q);return photos.filter(p=>match(p,a)).map(p=>({p,s:score(p,q)})).sort((x,y)=>y.s-x.s||date(y.p)-date(x.p)).slice(0,120).map(x=>x.p)}
  function style(){if(document.getElementById('smartSearchStyle'))return;const s=document.createElement('style');s.id='smartSearchStyle';s.textContent='.smart-search-modal{position:fixed;inset:0;z-index:90;background:rgba(8,10,16,.58);backdrop-filter:blur(22px);display:grid;place-items:center;padding:16px}.smart-search-shell{width:min(1120px,100%);max-height:90vh;overflow:auto;border:1px solid rgba(255,255,255,.35);border-radius:28px;background:rgba(248,249,252,.94);box-shadow:0 30px 100px rgba(0,0,0,.3);padding:20px}.smart-search-head{display:flex;gap:12px;align-items:center}.smart-search-input{flex:1;border:0;outline:0;border-radius:18px;padding:15px 17px;font:600 16px Inter,sans-serif;background:rgba(0,0,0,.06)}.smart-search-close{border:0;border-radius:14px;width:44px;height:44px;font-size:22px;cursor:pointer}.smart-search-hint{font-size:12px;color:#6b7280;margin:10px 2px}.smart-search-chips{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.smart-search-chip{border:0;border-radius:999px;padding:8px 12px;background:rgba(0,0,0,.06);cursor:pointer}.smart-search-results{display:grid;grid-template-columns:repeat(auto-fill,minmax(170px,1fr));gap:10px}.smart-result{border:0;border-radius:18px;overflow:hidden;padding:0;background:rgba(255,255,255,.65);text-align:left;cursor:pointer}.smart-result img{width:100%;aspect-ratio:1;object-fit:cover;display:block}.smart-result div{padding:9px}.smart-result strong,.smart-result small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.smart-result small{color:#6b7280;margin-top:3px}.smart-search-count{font-weight:700;margin:14px 0 10px}.smart-search-empty{text-align:center;padding:50px;color:#6b7280}@media(prefers-color-scheme:dark){.smart-search-shell{background:rgba(22,24,30,.95);color:#fff}.smart-search-input,.smart-search-chip,.smart-search-close{background:rgba(255,255,255,.08);color:#fff}.smart-search-hint,.smart-result small{color:#9ca3af}.smart-result{background:rgba(255,255,255,.06)}}';document.head.appendChild(s)}
  function render(root,q){const results=run(q);root.querySelector('.smart-search-count').textContent=q?`${results.length} matching photos`:'Try a natural search';const box=root.querySelector('.smart-search-results');box.innerHTML=results.map((p,i)=>{const a=visionCache.get(p.path||p.url||p.name)||{};return `<button class="smart-result" data-i="${i}"><img loading="lazy" src="${esc(p.thumbnail||url(p))}" alt=""><div><strong>${esc(p.name||'Photo')}</strong><small>${esc((a.labels||a.tags||[]).slice(0,3).join(' · ')||[p.year||'',p.month||''].filter(Boolean).join(' · '))}</small></div></button>`}).join('')||'<div class="smart-search-empty">No photos match that search.</div>';box.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{const p=results[+b.dataset.i];if(p)window.open(url(p),'_blank','noopener')})}
  async function openModal(){if(open)return;open=true;style();const m=document.createElement('div');m.className='smart-search-modal';m.innerHTML='<div class="smart-search-shell"><div class="smart-search-head"><input class="smart-search-input" autofocus placeholder="Search photos, AI labels, tags or captions…"><button class="smart-search-close">×</button></div><div class="smart-search-hint">Search combines filename/date metadata with locally generated AI Vision labels. Nothing is sent to a search API.</div><div class="smart-search-chips"><button class="smart-search-chip">Portraits from 2025</button><button class="smart-search-chip">Large photos</button><button class="smart-search-chip">Landscape 2026</button><button class="smart-search-chip">Food</button><button class="smart-search-chip">Travel</button><button class="smart-search-chip">Screenshot</button></div><div class="smart-search-count"></div><div class="smart-search-results"></div></div>';document.body.append(m);m.querySelector('.smart-search-close').onclick=close;const input=m.querySelector('input');const renderNow=()=>render(m,input.value);input.oninput=renderNow;m.querySelectorAll('.smart-search-chip').forEach(c=>c.onclick=()=>{input.value=c.textContent;renderNow();input.focus()});m.onclick=e=>{if(e.target===m)close()};(await loadVision()).forEach(a=>visionCache.set(a.key,a));renderNow();input.focus()}
  function close(){document.querySelector('.smart-search-modal')?.remove();open=false}
  async function load(){try{const r=await fetch(`${DATA_URL}?smartsearch=${Date.now()}`);const d=await r.json();photos=d.images||[]}catch(e){photos=[]}}
  function addButton(){const t=document.querySelector('.toolbar');if(!t||document.getElementById('smartSearchBtn'))return;const b=document.createElement('button');b.id='smartSearchBtn';b.className='icon-btn';b.setAttribute('aria-label','Smart search');b.textContent='⌕';b.onclick=openModal;t.insertBefore(b,t.firstChild)}
  window.PhotoSmartSearch={open:openModal,search:run};load().then(addButton);window.addEventListener('load',addButton);
})();
